name: Deploy Gemini25Pro App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/global-value-web/whatsappfor1.8release-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            IMAGE_NAME=ghcr.io/global-value-web/whatsappfor1.8release-app:latest
            docker login ghcr.io -u Global-Value-Web -p ${{ secrets.PAT }}
            docker pull $IMAGE_NAME
            docker stop whatsappfor1.8release-app || true
            docker rm whatsappfor1.8release-app || true
            docker run -d --restart=always -p 8000:8000 --name whatsappfor1.8release-app $IMAGE_NAME
