name: Deploy Flask App

on:
  push:
    branches: [ "main" ]  # deploy only after merg

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows, X64]   #  use your runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Global-Value-Web
          password: ${{ secrets.CR_PAT }}

 

      - name: Build and push Docker image
        run: |
          $IMAGE_NAME="ghcr.io/global-value-web/mail_trigger_app:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy on same server
        run: |
          $IMAGE_NAME="ghcr.io/global-value-web/mail_trigger_app:latest"
          docker pull $IMAGE_NAME
          # Stop container if it exists
          if (docker ps -a -q -f name=mail_trigger_app) {
             docker stop mail_trigger_app
             docker rm mail_trigger_app
          }
          docker run -d --restart=always -p 6020:6020 --name mail_trigger_app -e FROM_ADDRESS=${{ secrets.FROM_ADDRESS }} -e ACCOUNT_NAME=${{ secrets.ACCOUNT_NAME }} -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} $IMAGE_NAME
